<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..riVO2_' shared service.

return $this->privates['.service_locator..riVO2_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\MainController::home' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\NewsletterController::export' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\MainController:home' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\NewsletterController:export' => ['privates', '.service_locator.FufKbwa', 'get_ServiceLocator_FufKbwaService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
], [
    'App\\Controller\\MainController::home' => '?',
    'App\\Controller\\NewsletterController::export' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\MainController:home' => '?',
    'App\\Controller\\NewsletterController:export' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
