<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.sHx_eui' shared service.

return $this->privates['.service_locator.sHx_eui'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService.php', true],
    'newsletter' => ['privates', '.errored..service_locator.sHx_eui.App\\Entity\\Newsletter', NULL, 'Cannot autowire service ".service_locator.sHx_eui": it references class "App\\Entity\\Newsletter" but no such service exists.'],
], [
    'manager' => '?',
    'newsletter' => 'App\\Entity\\Newsletter',
]);
