easy_admin:

  list:
    actions: ['edit', 'search']

  user:
    display_name: true
    display_avatar: false
    name_property_path: 'username'

  formats:
    date: 'd/m/Y'
    time: 'H:i'
    datetime: 'd/m/Y H:i:s' 

  site_name: 'OWL Administration'

  design:
    brand_color: '#FFA500'

  entities:
    User:
      label: 'Utilisateur'
      class: App\Entity\User
      form:
        fields:
          - { property: 'username', label: "Nom d'utilisateur"}
          - { property: 'email', label: "Email"}
          - { property: 'roles', label: "Rôle"}
      list:
        actions:
          - { name: 'edit', icon: 'wrench', label: false, title: 'Editer'}
          - { name: 'delete', icon: 'trash', label: false, title: 'Supprimer' }
        fields:
          - { property: 'id', label: "ID"}
          - { property: 'username', label: "Nom d'utilisateur"}
          - { property: 'email', label: "Email"}
          - { property: 'roles', label: "Rôle(s)"}

    Newsletter:
      label: 'Newsletter'
      class: App\Entity\Newsletter
      form:
        fields:
          - { property: 'email', label: 'Email'}
      list:
        actions:
          - { name: 'newsletter_export', icon: 'download', type: 'route', label: false, title: 'Exporter en .csv' }
          - { name: 'edit', icon: 'wrench', label: false, title: 'Editer' }
          - { name: 'delete', icon: 'trash', label: false, title: 'Supprimer' }
        fields:
          - { property: 'id', label: "ID"}
          - { property: 'email', label: "Email"}
          - { property: 'date', label: "Date"}
          - { property: 'isActive', label: "Activer"}






          

