<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '54535fdc4754bc66860d462801984337',
  'DATABASE_URL' => 'mysql://root:@127.0.0.1:3306/db_owl_eyewear',
  'MAILER_URL' => 'null://localhost',
);
