<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZNkk6ff\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZNkk6ff/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerZNkk6ff.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerZNkk6ff\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerZNkk6ff\srcApp_KernelProdContainer([
    'container.build_hash' => 'ZNkk6ff',
    'container.build_id' => '20c0eb0c',
    'container.build_time' => 1571140880,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZNkk6ff');
