<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRHx2KaS\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRHx2KaS/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRHx2KaS.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRHx2KaS\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerRHx2KaS\srcApp_KernelProdContainer([
    'container.build_hash' => 'RHx2KaS',
    'container.build_id' => 'f3776ae4',
    'container.build_time' => 1570371687,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRHx2KaS');
