<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.T0Y0dz_' shared service.

return $this->privates['.service_locator.T0Y0dz_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\NewsletterController::getNews' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
    'App\\Controller\\NewsletterController:getNews' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.czKK4py', 'get_ServiceLocator_CzKK4pyService.php', true],
], [
    'App\\Controller\\NewsletterController::getNews' => '?',
    'App\\Controller\\SecurityController::registration' => '?',
    'App\\Controller\\NewsletterController:getNews' => '?',
    'App\\Controller\\SecurityController:registration' => '?',
]);
