<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.4B_wQsK' shared service.

return $this->privates['.service_locator.4B_wQsK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'page' => ['privates', '.errored..service_locator.4B_wQsK.App\\Entity\\Page', NULL, 'Cannot autowire service ".service_locator.4B_wQsK": it references class "App\\Entity\\Page" but no such service exists.'],
], [
    'page' => 'App\\Entity\\Page',
]);
