<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFVMNkw8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFVMNkw8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFVMNkw8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFVMNkw8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerFVMNkw8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'FVMNkw8',
    'container.build_id' => '3badd198',
    'container.build_time' => 1569949924,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFVMNkw8');
